---
- name: Reset network connection
  hosts: all
  become: true

  tasks:
  - name: Ensure connection Production is UP
    community.general.nmcli:
      conn_name: 'Production'
      state: up
  - name: pass server to follow up jobs if any
    ansible.builtin.set_stats:
      data:
        server: "{{ inventory_hostname_short }}"
